# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29370312a23e4b1dfe4e583eb0aa847a81af170361759ad595c12a5e6ceefc226219be41144bbcadf103431e7abe3b8bd34ebaef36a8dbc6a9d23121bf2cf2dd

test:
  secret_key_base: 272aafed52912b0de769f9c4a2d1368b97390e5a4ff71fba9ae6f5f8408a6bd8fbc56dfa4fd309555e782a13c01bef65c2c93fae53ff06ad429c76a700f35c26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
